name: landify_design_flutter
description: "A Flutter web project implementing the Landify Landing Page UI Kit to explore and learn Flutter web development."
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  animate_gradient: ^0.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_layout_grid: ^2.0.7
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  syncfusion_flutter_maps: ^26.2.14

  device_frame: ^1.2.0
  shared_preferences: ^2.3.0
  aura_box: ^1.0.2

  # URL
  url_strategy: ^0.2.0
  url_launcher: ^6.3.0

  loading_animation_widget: ^1.2.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  riverpod_generator:
  riverpod_lint:
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/world_map.json
    - assets/servers.json
